// ============================================================
// MODULE: notification.types.ts
// Notification type and channel constants
// ============================================================

export const NOTIFICATION_TYPE_OBJECT = {
  ACCOUNT_APPROVED: "ACCOUNT_APPROVED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  JOIN_REQUEST_RECEIVED: "JOIN_REQUEST_RECEIVED",
  JOIN_REQUEST_ACCEPTED: "JOIN_REQUEST_ACCEPTED",
  JOIN_REQUEST_REJECTED: "JOIN_REQUEST_REJECTED",
  PAYMENT_SUBMITTED: "PAYMENT_SUBMITTED",
  PAYMENT_APPROVED: "PAYMENT_APPROVED",
  PAYMENT_REJECTED: "PAYMENT_REJECTED",
  ENROLLMENT_SUSPENDED: "ENROLLMENT_SUSPENDED",
  ENROLLMENT_REMOVED: "ENROLLMENT_REMOVED",
  ENROLLMENT_WAITLISTED: "ENROLLMENT_WAITLISTED",
  NEW_ANNOUNCEMENT: "NEW_ANNOUNCEMENT",
  NEW_TASK: "NEW_TASK",
  NEW_DAILY_NOTE: "NEW_DAILY_NOTE",
  NEW_MESSAGE: "NEW_MESSAGE",
  ATTENDANCE_MARKED: "ATTENDANCE_MARKED",
  GUARDIAN_LINK_REQUEST: "GUARDIAN_LINK_REQUEST",
  GUARDIAN_LINK_ACCEPTED: "GUARDIAN_LINK_ACCEPTED",
  FOLLOW_NEW: "FOLLOW_NEW",
  CLASS_CANCELLED: "CLASS_CANCELLED",
  CLASS_RESCHEDULED: "CLASS_RESCHEDULED",
} as const;

export const NOTIFICATION_CHANNEL_OBJECT = {
  IN_APP: "IN_APP",
  EMAIL: "EMAIL",
} as const;

export const NOTIFICATION_TYPES = {
  TYPES: Object.keys(NOTIFICATION_TYPE_OBJECT) as readonly string[],
  CHANNELS: Object.keys(NOTIFICATION_CHANNEL_OBJECT) as readonly string[],
  TYPE_OBJECT: NOTIFICATION_TYPE_OBJECT,
  CHANNEL_OBJECT: NOTIFICATION_CHANNEL_OBJECT,
} as const;

export type INotificationType = (typeof NOTIFICATION_TYPE_OBJECT)[keyof typeof NOTIFICATION_TYPE_OBJECT];
export type INotificationChannel = (typeof NOTIFICATION_CHANNEL_OBJECT)[keyof typeof NOTIFICATION_CHANNEL_OBJECT];
